print(len(localites_maroc = [
    "Banque Casablanca",
    "Banque Anfa",
    "Banque Sidi Bernoussi",
    "Banque Aïn Sebaâ",
    "Banque Mohammédia",
    "Banque Rabat",
    "Banque Salé",
    "Banque Temara",
    "Banque Fès",
    "Banque Meknès",
    "Banque Tanger",
    "Banque Tétouan",
    "Banque Martil",
    "Banque Oujda",
    "Banque Nador",
    "Banque Berkane",
    "Banque Ahfir",
    "Banque Zaio",
    "Banque Agadir",
    "Banque Inezgane",
    "Banque Aït Melloul",
    "Banque Marrakech",
    "Banque Essaouira",
    "Banque Safi",
    "Banque El Jadida",
    "Banque Azemmour",
    "Banque Sidi Bennour",
    "Banque Settat",
    "Banque Berrechid",
    "Banque Khouribga",
    "Banque Béni Mellal",
    "Banque Fquih Ben Salah",
    "Banque Ouarzazate",
    "Banque Skoura",
    "Banque Tinghir",
    "Banque Errachidia",
    "Banque Tiznit",
    "Banque Laâyoune",
    "Banque Dakhla",
    "Banque Smara",
    "Banque Boujdour",
    "Banque Tan-Tan",
    "Banque Guelmim",
    "Banque Taroudant",
    "Banque Taliouine",
    "Banque Aoulouz",
    "Banque Kénitra",
    "Banque Sidi Slimane",
    "Banque Sidi Yahya El Gharb",
    "Banque Larache",
    "Banque Asilah",
    "Banque Chefchaouen",
    "Banque Oued Laou",
    "Banque Al Hoceima",
    "Banque Imzouren",
    "Banque Bni Bouayach",
    "Banque Taourirt",
    "Banque Guercif",
    "Banque Tafoughalt",
    "Banque Sidi Kacem",
    "Banque Mechra Bel Ksiri",
    "Banque Azrou",
    "Banque Ifrane",
    "Banque Timahdite",
    "Banque Midelt",
    "Banque Rich",
    "Banque Zaouiat Cheikh",
    "Banque Oulmès",
    "Banque Boulemane",
    "Banque Outat El Haj",
    "Banque Bouarfa",
    "Banque Figuig",
    "Banque Aknoul",
    "Banque Tahla",
    "Banque Ahermoumou",
    "Banque Bouizakarne",
    "Banque Taghjijt",
    "Banque Ait Baha",
    "Banque Tafraout",
    "Banque Imi N'Tanoute",
    "Banque Chichaoua",
    "Banque Amizmiz",
    "Banque Tamazouzt",
    "Banque Demnate",
    "Banque Skhour Rhamna",
    "Banque Ben Guerir"
]
))